/**
 * Core Data Contracts for Step Frame Execution Traces
 */

export const STEP_ACTIONS = {
  VAR_DECLARATION: 'VAR_DECLARATION',
  ASSIGNMENT: 'ASSIGNMENT',
  FUNCTION_CALL: 'FUNCTION_CALL',
  FUNCTION_RETURN: 'FUNCTION_RETURN',
  CONDITION_EVAL: 'CONDITION_EVAL',
  LOOP_ITERATION: 'LOOP_ITERATION',
  ARRAY_MUTATION: 'ARRAY_MUTATION',
  CONSOLE_LOG: 'CONSOLE_LOG'
};

export const NODE_STATES = {
  DEFAULT: 'DEFAULT',
  ACTIVE: 'ACTIVE',
  COMPARING: 'COMPARING',
  SWAPPING: 'SWAPPING',
  SORTED: 'SORTED',
  VISITED: 'VISITED'
};
